//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ResumeModel", "FK_UserResume", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ResumeBuilder.Core.User), "Resume", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ResumeBuilder.Core.Resume), true)]

#endregion

namespace ResumeBuilder.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ResumeModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ResumeModelContainer object using the connection string found in the 'ResumeModelContainer' section of the application configuration file.
        /// </summary>
        public ResumeModelContainer() : base("name=ResumeModelContainer", "ResumeModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ResumeModelContainer object.
        /// </summary>
        public ResumeModelContainer(string connectionString) : base(connectionString, "ResumeModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ResumeModelContainer object.
        /// </summary>
        public ResumeModelContainer(EntityConnection connection) : base(connection, "ResumeModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Resume> Resumes
        {
            get
            {
                if ((_Resumes == null))
                {
                    _Resumes = base.CreateObjectSet<Resume>("Resumes");
                }
                return _Resumes;
            }
        }
        private ObjectSet<Resume> _Resumes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<School> Schools
        {
            get
            {
                if ((_Schools == null))
                {
                    _Schools = base.CreateObjectSet<School>("Schools");
                }
                return _Schools;
            }
        }
        private ObjectSet<School> _Schools;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkExperience> WorkExperiences
        {
            get
            {
                if ((_WorkExperiences == null))
                {
                    _WorkExperiences = base.CreateObjectSet<WorkExperience>("WorkExperiences");
                }
                return _WorkExperiences;
            }
        }
        private ObjectSet<WorkExperience> _WorkExperiences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkExpPosition> WorkExpPositions
        {
            get
            {
                if ((_WorkExpPositions == null))
                {
                    _WorkExpPositions = base.CreateObjectSet<WorkExpPosition>("WorkExpPositions");
                }
                return _WorkExpPositions;
            }
        }
        private ObjectSet<WorkExpPosition> _WorkExpPositions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Resumes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResumes(Resume resume)
        {
            base.AddObject("Resumes", resume);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schools EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchools(School school)
        {
            base.AddObject("Schools", school);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkExperiences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkExperiences(WorkExperience workExperience)
        {
            base.AddObject("WorkExperiences", workExperience);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkExpPositions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkExpPositions(WorkExpPosition workExpPosition)
        {
            base.AddObject("WorkExpPositions", workExpPosition);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResumeModel", Name="Resume")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Resume : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Resume object.
        /// </summary>
        /// <param name="resumeIDKey">Initial value of the ResumeIDKey property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="middleName">Initial value of the MiddleName property.</param>
        /// <param name="missionStatement">Initial value of the MissionStatement property.</param>
        /// <param name="school">Initial value of the School property.</param>
        /// <param name="certifications">Initial value of the Certifications property.</param>
        /// <param name="jobExperience">Initial value of the JobExperience property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="userUserIDKey">Initial value of the UserUserIDKey property.</param>
        public static Resume CreateResume(global::System.Int32 resumeIDKey, global::System.DateTime lastUpdated, global::System.String firstName, global::System.String lastName, global::System.String middleName, global::System.String missionStatement, global::System.String school, global::System.String certifications, global::System.String jobExperience, global::System.String email, global::System.String phoneNumber, global::System.Int32 userUserIDKey)
        {
            Resume resume = new Resume();
            resume.ResumeIDKey = resumeIDKey;
            resume.LastUpdated = lastUpdated;
            resume.FirstName = firstName;
            resume.LastName = lastName;
            resume.MiddleName = middleName;
            resume.MissionStatement = missionStatement;
            resume.School = school;
            resume.Certifications = certifications;
            resume.JobExperience = jobExperience;
            resume.Email = email;
            resume.PhoneNumber = phoneNumber;
            resume.UserUserIDKey = userUserIDKey;
            return resume;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResumeIDKey
        {
            get
            {
                return _ResumeIDKey;
            }
            set
            {
                if (_ResumeIDKey != value)
                {
                    OnResumeIDKeyChanging(value);
                    ReportPropertyChanging("ResumeIDKey");
                    _ResumeIDKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResumeIDKey");
                    OnResumeIDKeyChanged();
                }
            }
        }
        private global::System.Int32 _ResumeIDKey;
        partial void OnResumeIDKeyChanging(global::System.Int32 value);
        partial void OnResumeIDKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MissionStatement
        {
            get
            {
                return _MissionStatement;
            }
            set
            {
                OnMissionStatementChanging(value);
                ReportPropertyChanging("MissionStatement");
                _MissionStatement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MissionStatement");
                OnMissionStatementChanged();
            }
        }
        private global::System.String _MissionStatement;
        partial void OnMissionStatementChanging(global::System.String value);
        partial void OnMissionStatementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String School
        {
            get
            {
                return _School;
            }
            set
            {
                OnSchoolChanging(value);
                ReportPropertyChanging("School");
                _School = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("School");
                OnSchoolChanged();
            }
        }
        private global::System.String _School;
        partial void OnSchoolChanging(global::System.String value);
        partial void OnSchoolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Certifications
        {
            get
            {
                return _Certifications;
            }
            set
            {
                OnCertificationsChanging(value);
                ReportPropertyChanging("Certifications");
                _Certifications = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Certifications");
                OnCertificationsChanged();
            }
        }
        private global::System.String _Certifications;
        partial void OnCertificationsChanging(global::System.String value);
        partial void OnCertificationsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobExperience
        {
            get
            {
                return _JobExperience;
            }
            set
            {
                OnJobExperienceChanging(value);
                ReportPropertyChanging("JobExperience");
                _JobExperience = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JobExperience");
                OnJobExperienceChanged();
            }
        }
        private global::System.String _JobExperience;
        partial void OnJobExperienceChanging(global::System.String value);
        partial void OnJobExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserUserIDKey
        {
            get
            {
                return _UserUserIDKey;
            }
            set
            {
                OnUserUserIDKeyChanging(value);
                ReportPropertyChanging("UserUserIDKey");
                _UserUserIDKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserUserIDKey");
                OnUserUserIDKeyChanged();
            }
        }
        private global::System.Int32 _UserUserIDKey;
        partial void OnUserUserIDKeyChanging(global::System.Int32 value);
        partial void OnUserUserIDKeyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResumeModel", "FK_UserResume", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ResumeModel.FK_UserResume", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ResumeModel.FK_UserResume", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ResumeModel.FK_UserResume", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ResumeModel.FK_UserResume", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResumeModel", Name="School")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class School : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new School object.
        /// </summary>
        /// <param name="schoolId">Initial value of the SchoolId property.</param>
        /// <param name="schoolName">Initial value of the SchoolName property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="major">Initial value of the Major property.</param>
        /// <param name="resumeIDKey">Initial value of the ResumeIDKey property.</param>
        public static School CreateSchool(global::System.Int32 schoolId, global::System.String schoolName, global::System.DateTime startDate, global::System.DateTime endDate, global::System.String major, global::System.String resumeIDKey)
        {
            School school = new School();
            school.SchoolId = schoolId;
            school.SchoolName = schoolName;
            school.StartDate = startDate;
            school.EndDate = endDate;
            school.Major = major;
            school.ResumeIDKey = resumeIDKey;
            return school;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SchoolId
        {
            get
            {
                return _SchoolId;
            }
            set
            {
                if (_SchoolId != value)
                {
                    OnSchoolIdChanging(value);
                    ReportPropertyChanging("SchoolId");
                    _SchoolId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SchoolId");
                    OnSchoolIdChanged();
                }
            }
        }
        private global::System.Int32 _SchoolId;
        partial void OnSchoolIdChanging(global::System.Int32 value);
        partial void OnSchoolIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SchoolName
        {
            get
            {
                return _SchoolName;
            }
            set
            {
                OnSchoolNameChanging(value);
                ReportPropertyChanging("SchoolName");
                _SchoolName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SchoolName");
                OnSchoolNameChanged();
            }
        }
        private global::System.String _SchoolName;
        partial void OnSchoolNameChanging(global::System.String value);
        partial void OnSchoolNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Major
        {
            get
            {
                return _Major;
            }
            set
            {
                OnMajorChanging(value);
                ReportPropertyChanging("Major");
                _Major = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Major");
                OnMajorChanged();
            }
        }
        private global::System.String _Major;
        partial void OnMajorChanging(global::System.String value);
        partial void OnMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResumeIDKey
        {
            get
            {
                return _ResumeIDKey;
            }
            set
            {
                OnResumeIDKeyChanging(value);
                ReportPropertyChanging("ResumeIDKey");
                _ResumeIDKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResumeIDKey");
                OnResumeIDKeyChanged();
            }
        }
        private global::System.String _ResumeIDKey;
        partial void OnResumeIDKeyChanging(global::System.String value);
        partial void OnResumeIDKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResumeModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userIDKey">Initial value of the UserIDKey property.</param>
        /// <param name="testValue">Initial value of the TestValue property.</param>
        public static User CreateUser(global::System.Int32 userIDKey, global::System.String testValue)
        {
            User user = new User();
            user.UserIDKey = userIDKey;
            user.TestValue = testValue;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserIDKey
        {
            get
            {
                return _UserIDKey;
            }
            set
            {
                if (_UserIDKey != value)
                {
                    OnUserIDKeyChanging(value);
                    ReportPropertyChanging("UserIDKey");
                    _UserIDKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserIDKey");
                    OnUserIDKeyChanged();
                }
            }
        }
        private global::System.Int32 _UserIDKey;
        partial void OnUserIDKeyChanging(global::System.Int32 value);
        partial void OnUserIDKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TestValue
        {
            get
            {
                return _TestValue;
            }
            set
            {
                OnTestValueChanging(value);
                ReportPropertyChanging("TestValue");
                _TestValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TestValue");
                OnTestValueChanged();
            }
        }
        private global::System.String _TestValue;
        partial void OnTestValueChanging(global::System.String value);
        partial void OnTestValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ResumeModel", "FK_UserResume", "Resume")]
        public EntityCollection<Resume> Resumes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Resume>("ResumeModel.FK_UserResume", "Resume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Resume>("ResumeModel.FK_UserResume", "Resume", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResumeModel", Name="WorkExperience")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkExperience : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkExperience object.
        /// </summary>
        /// <param name="workExperienceId">Initial value of the WorkExperienceId property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="resumeIDKey">Initial value of the ResumeIDKey property.</param>
        public static WorkExperience CreateWorkExperience(global::System.Int32 workExperienceId, global::System.DateTime startDate, global::System.DateTime endDate, global::System.String resumeIDKey)
        {
            WorkExperience workExperience = new WorkExperience();
            workExperience.WorkExperienceId = workExperienceId;
            workExperience.StartDate = startDate;
            workExperience.EndDate = endDate;
            workExperience.ResumeIDKey = resumeIDKey;
            return workExperience;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkExperienceId
        {
            get
            {
                return _WorkExperienceId;
            }
            set
            {
                if (_WorkExperienceId != value)
                {
                    OnWorkExperienceIdChanging(value);
                    ReportPropertyChanging("WorkExperienceId");
                    _WorkExperienceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkExperienceId");
                    OnWorkExperienceIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkExperienceId;
        partial void OnWorkExperienceIdChanging(global::System.Int32 value);
        partial void OnWorkExperienceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResumeIDKey
        {
            get
            {
                return _ResumeIDKey;
            }
            set
            {
                OnResumeIDKeyChanging(value);
                ReportPropertyChanging("ResumeIDKey");
                _ResumeIDKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResumeIDKey");
                OnResumeIDKeyChanged();
            }
        }
        private global::System.String _ResumeIDKey;
        partial void OnResumeIDKeyChanging(global::System.String value);
        partial void OnResumeIDKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ResumeModel", Name="WorkExpPosition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkExpPosition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkExpPosition object.
        /// </summary>
        /// <param name="workExpPosId">Initial value of the WorkExpPosId property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="responsibility">Initial value of the Responsibility property.</param>
        /// <param name="workTitle">Initial value of the WorkTitle property.</param>
        /// <param name="workExperienceId">Initial value of the WorkExperienceId property.</param>
        public static WorkExpPosition CreateWorkExpPosition(global::System.Int32 workExpPosId, global::System.DateTime startDate, global::System.DateTime endDate, global::System.String responsibility, global::System.String workTitle, global::System.String workExperienceId)
        {
            WorkExpPosition workExpPosition = new WorkExpPosition();
            workExpPosition.WorkExpPosId = workExpPosId;
            workExpPosition.StartDate = startDate;
            workExpPosition.EndDate = endDate;
            workExpPosition.Responsibility = responsibility;
            workExpPosition.WorkTitle = workTitle;
            workExpPosition.WorkExperienceId = workExperienceId;
            return workExpPosition;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkExpPosId
        {
            get
            {
                return _WorkExpPosId;
            }
            set
            {
                if (_WorkExpPosId != value)
                {
                    OnWorkExpPosIdChanging(value);
                    ReportPropertyChanging("WorkExpPosId");
                    _WorkExpPosId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkExpPosId");
                    OnWorkExpPosIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkExpPosId;
        partial void OnWorkExpPosIdChanging(global::System.Int32 value);
        partial void OnWorkExpPosIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Responsibility
        {
            get
            {
                return _Responsibility;
            }
            set
            {
                OnResponsibilityChanging(value);
                ReportPropertyChanging("Responsibility");
                _Responsibility = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Responsibility");
                OnResponsibilityChanged();
            }
        }
        private global::System.String _Responsibility;
        partial void OnResponsibilityChanging(global::System.String value);
        partial void OnResponsibilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WorkTitle
        {
            get
            {
                return _WorkTitle;
            }
            set
            {
                OnWorkTitleChanging(value);
                ReportPropertyChanging("WorkTitle");
                _WorkTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WorkTitle");
                OnWorkTitleChanged();
            }
        }
        private global::System.String _WorkTitle;
        partial void OnWorkTitleChanging(global::System.String value);
        partial void OnWorkTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WorkExperienceId
        {
            get
            {
                return _WorkExperienceId;
            }
            set
            {
                OnWorkExperienceIdChanging(value);
                ReportPropertyChanging("WorkExperienceId");
                _WorkExperienceId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WorkExperienceId");
                OnWorkExperienceIdChanged();
            }
        }
        private global::System.String _WorkExperienceId;
        partial void OnWorkExperienceIdChanging(global::System.String value);
        partial void OnWorkExperienceIdChanged();

        #endregion
    
    }

    #endregion
    
}
